### ISSUE TITLE
Missing files ?

### ISSUE THREAD

**Issue by Krammig** [kalli-st/conversations#3]
Thanks for sharing. Just trying to take a look. 

It appears there are a few files missing. 

For example   ActivityEasyInviteBinding.java

Appreciate if you could look inti that. 
Thanks

**Comment by kzarist** [comment]
I don't think there is something missing the project was auto built with CI
https://github.com/kalli-st/conversations/releases

This version is not maintained anymore we have a new fork at https://gt.kalli.st/czar/fnord
